### ISSUE TITLE
MeteoGalicia url not working

### ISSUE THREAD

**Issue by rbessa** [oscarperpinan/meteoForecast#16]
Dear Oscar,
the MeteoGalicia url for downloading the file is not working. For example: 

http://mandeo.meteogalicia.es/thredds/ncss/grid/wrf_2d_12km/fmrc/files/20150911/wrf_arw_det_history_d02_20150911_0000.nc4?var=cfh,cfl,cfm,cft,dir,lwflx,mod,mslp,rh,temp,swflx,u,v,wind_gust&point=true&longitude=-7.910888&latitude=38.57118

**Comment by oscarperpinan** [comment]
Hello,

Their THREDDS servers seem to be down. I have checked both [MANDEO](http://mandeo.meteogalicia.es/thredds/) and [SOR](http://sor.meteogalicia.es/thredds/catalog.html) without success. 

We have to wait.

**Comment by rbessa** [comment]
Now the MANDEO is working but the url for downloading the data is empty. 

Error in pointMG(lon = -7.910888, lat = 38.57118, vars = c("cfh", "cfl",  : 
  Data not found. Check the date and variables name.
URL: http://mandeo.meteogalicia.es/thredds/ncss/grid/wrf_2d_12km/fmrc/files/20151129/wrf_arw_det_history_d02_20151129_0000.nc4?var=cfh,cfl,cfm,cft,dir,lwflx,mod,mslp,rh,temp,swflx,u,v,wind_gust&point=true&longitude=-7.910888&latitude=38.57118

I will try to contact them to see if this is temporary.

**Comment by oscarperpinan** [comment]
Maybe it is related to recent changes in their THREDDS server. I will check again the documentation.
