### ISSUE TITLE
NOMADS web services have transitioned to use of HTTPS and HSTS.

### ISSUE THREAD

**Issue by mondorescue** [oscarperpinan/meteoForecast#19]
When I run

`grepVar("", service = 'gfs', complete = TRUE)`

I get the following error

`Unknown IO errorfailed to load external entity "http://nomads.ncdc.noaa.gov/thredds/wcs/gfs-004/201702/20170202/gfs_4_20170202_0000_000.grb2?service=WCS&version=1.0.0&request=GetCapabilities"
Error: 1: Unknown IO error2: failed to load external entity "http://nomads.ncdc.noaa.gov/thredds/wcs/gfs-004/201702/20170202/gfs_4_20170202_0000_000.grb2?service=WCS&version=1.0.0&request=GetCapabilities"`

When I try to access:

[**http**://nomads.ncdc.noaa.gov/thredds/wcs/gfs-004/201702/20170202/gfs_4_20170202_0000_000.grb2?service=WCS&version=1.0.0&request=GetCapabilities](url)

in my web browser (Google Chrome), it redirects me to

[**https**://nomads.ncdc.noaa.gov/thredds/wcs/gfs-004/201702/20170202/gfs_4_20170202_0000_000.grb2?service=WCS&version=1.0.0&request=GetCapabilities](url)

Can the URL that grepVars use be changed from http to https?

Thanks

**Comment by mondorescue** [comment]
I made a pull request with the update to the URL protocol from http to https. I also made minor changes so that xmlParse can parse the resulting xml from NOMADS https. See pull request for more detail.

**Comment by oscarperpinan** [comment]
Hello,

Sorry for my delay in giving you an answer. I had a problem with the github notifications settings.
I will try to review this problem as soon as possible. Thanks for the info and the code.
