### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by mbacou** [oscarperpinan/meteoForecast#24]
Has someone taken over maintenance of this package? Is it still working for the 4 data sources listed in the doco:
- GFS
- MeteoGalicia
- NAM
- RAP

Thanks!

**Comment by oscarperpinan** [comment]
> Has someone taken over maintenance of this package?
No changes. Although I have less time for this package than in the past, I am still the maintainer.

> Is it still working for the 4 data sources listed in the docs:
I am sure you have try them all before opening this issue:

- GFS: not working, to be fixed soon (I will use a different server).
- MeteoGalicia: working correctly.
- NAM: not working, easy to fix. 
- RAP: not working, easy to fix.

**Comment by mbacou** [comment]
Actually no, I didn't try, just inspected the source quickly, but really appreciate the clarification and fixes above!

My organization maintains a package with a similar scope (incl. access to additional weather models, e.g. TAMSAT, CHIRPS, ERA5-LAND). Access to NAM  historical archives has been a struggle so far, we will give it a shot. (cc. @jlehnny).

**Comment by mbacou** [comment]
@oscarperpinan quick check on our end, seems like the model names have also been updated from `nam218` to `model-nam218` (same with `namanl` and `model-namanl`.

```r
library(raster)
library(meteoForecast)

mfService("nam")
v <- grepVar("", service="nam", day=as.Date("2020-11-23"), complete=FALSE)

# This URL fails:
# https://www.ncei.noaa.gov/thredds/wcs/nam218/202011/20201123/nam_218_20201123_0000_001.grb2?service=WCS&version=1.0.0&request=GetCapabilities

# But this works
# https://www.ncei.noaa.gov/thredds/wcs/model-nam218/202011/20201123/nam_218_20201123_0000_000.grb2?service=WCS&version=1.0.0&request=GetCapabilities
```

**Comment by oscarperpinan** [comment]
> My organization maintains a package with a similar scope (incl. access to additional weather models, e.g. TAMSAT, CHIRPS, ERA5-LAND). Access to NAM historical archives has been a struggle so far, but we never tried to access UCAR THREDDS server directly. 

@mbacou I have committed several changes in the code (see above). With these changes both RAP and NAM work again, and GFS too but using the MeteoGalicia server instead of the NCEI server. The configuration of this server makes the retrieval of data very slow in comparison with the Meteogalicia server. The drawback is that the geographical extent is limited and MG does not store historical data of GFS.

Although I have not finished the update, I would appreciate if you could give the package a try. 

```
## install.packages("remotes")
remotes::install_github("oscarperpinan/meteoForecast")
```

Comments are welcome.

> Not related, but would you happen to know if there an organization equivalent to MeteoGalicia for Extremadura with downsampled weather models?

No idea, I am sorry.
