### ISSUE TITLE
Descargar un nivel concreto de presión

### ISSUE THREAD

**Issue by lemuscanovas** [oscarperpinan/meteoForecast#25]
Buenas tardes,

Antes de nada, felicitaros por la librería. Me parece muy útil!
Estaba intentando descargar los rasters la altura geopotencial a 500 hPa del GFS, pero no veo de que manera puedo seleccionar el nivel vertical de presión. Quizás no hay opción de descargar variables a distintos niveles de presión?

Gracias de antemano!

**Comment by oscarperpinan** [comment]
Hola.
Lo siento, pero esa opción no está implementada en meteoForecast. Como alternativa, puedes utilizar la URL que genera `getRaster` (o la función que te interese) y modificarla manualmente añadiendo la información del nivel para descargar el fichero que te interese.

Saludos,

Oscar.

**Comment by lemuscanovas** [comment]
Hola Óscar. 
Al final opté por crearme mis propias funciones para bajar los datos del GFS a 0.25º,0.5 y 1º de cualquier variable. Gracias igualmente!
