### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [oscarperpinan/meteoForecast#27]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by oscarperpinan** [comment]
Hi.

This package suggests `rgdal` to use the `spTransform` method. According to the `sp` documentation, "Package rgdal provides the methods doing actual transformation; when rgdal cannot be loaded, an error message."

**Comment by rsbivand** [comment]
Please see both blogs. Until June 2023, the **sp** evolution status option/environment variable (must be set before loading) is default 0, but can be set to 2 to use **sf** rather than **rgdal**. Please raise an issue if you also need to set/reset it id **sp** is already loaded on https://github.com/r-spatial/evolution/issues.
